
#ifndef _APP_CONFIG_H_
#define _APP_CONFIG_H_

#define NRF_LOG_ENABLED 0

#define NRF_LOG_DEFERRED 0

#define APP_TIMER_ENABLED 1
#define APP_SCHEDULER_ENABLED 1
#define APP_TIMER_CONFIG_USE_SCHEDULER 0

#define WDT_ENABLED 1

#define NRF_LOG_BACKEND_SERIAL_USES_RTT 1
#define NRF_LOG_BACKEND_SERIAL_USES_UART 0

#endif /* _APP_CONFIG_H_ */

